modLoader="javafml"
loaderVersion="[41,47)"
license="GNU General Public License 3.0"
issueTrackerURL="https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues"

[[mods]]
modId="vehicle"
version="0.46.3-19.4"
displayName="MrCrayfish's Vehicle Mod"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=vehicle"
displayURL="https://mrcrayfish.com/mods?id=vehicle"
logoFile="vehicle_mod.png"
credits="""Mrcrayfish [ owner/author ],

ItsUniqueGamer [ responsible for porting the mod to newer versions],

xitzfinex [ responsible for helping with texture issues in the ports ],

Mr22seal [ helped with fixing crashes with dirt bike and moped and also created universal posture ]"""

authors="MrCrayfish, ItsUniqueGamer"
description="""A mod that adds vehicles into Minecraft!

Warning: This is an unofficial port of the mod.
Please do not report any crashes, bugs or issues regarding this version or port of the mod to mrcrayfish.
Any issues or bugs found must reported to ItsUniqueGamer via mrcrayfish server, DM or MCMPC server
Join the Minecraft Mod Porting Community: https://dsc.gg/MCMPC"""

[[dependencies.vehicle]]
modId="forge"
mandatory=true
versionRange="[45.3.3,47)"
ordering="NONE"
side="BOTH"
[[dependencies.vehicle]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.vehicle]]
modId="framework"
mandatory=true
versionRange="[0.7.10,)"
ordering="AFTER"
side="BOTH"
[[dependencies.vehicle]]
modId="posture"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"